### ISSUE TITLE
Allow retrieval of a subset of data fields / properties via query parameter

### ISSUE THREAD

**Issue by johnkramlich** [CivilServiceUSA/api#36]
#### Overview:

Allow API consumers to specify what fields they want to have returned in an API response.  Facebook uses a syntax like the following:

`https://graph.facebook.com/me?fields=id,name,picture`

Which would return a response like:

```javascript
{
  "id": "887805633",
  "name": "John Kramlich",
  "picture": {
    "data": {
      "is_silhouette": false,
      "url": "https://scontent.xx.fbcdn.net/v/t1.0-1/c0.9.50.50/p50x50/10525372_10154464267735634_677466647805040812_n.jpg?oh=e1560580f9b685b9b3d46ac3472febd6&oe=5925473D"
    }
  }
}
```

#### Acceptance Criteria:

For any endpoint where the request was made with a `fields` query parameter.  Only return those fields in the response.  Otherwise, return a default set of fields.

#### Relevant Documentation

[Example Facebook Graph API Explorer](https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=me%3Ffields%3Did%2Cname&version=v2.8)

**Comment by manifestinteractive** [comment]
This is a pretty sweet idea @johnkramlich and should be pretty easy to implement

**Comment by manifestinteractive** [comment]
This feature is now available :)
