### ISSUE TITLE
Invalid GeoJSON Indexing in ElasticSearch

### ISSUE THREAD

**Issue by manifestinteractive** [CivilServiceUSA/api#37]
#### Overview:

There are few tables in our database with a `shape` column: `house`, `senate`, `state` & `zipcode`.  ElasticSearch indexes this column for GeoSpatial searches.  However, it seems that some of the data we have is not valid, and therefore not being indexed correctly by ElasticSearch.

#### Acceptance Criteria:

All `geometry` data in the `shape` column of the `house`, `senate`, `state` & `zipcode` tables should be valid.

#### Steps to Duplicate:

```sql
SELECT ST_IsValid(h.shape), h.* FROM `house` h WHERE ST_IsValid(h.shape) = 0;
```

`house` has `37` Invalid Records of 427 ( 11% Invalid )

```sql
SELECT ST_IsValid(s.shape), s.* FROM `senate` s WHERE ST_IsValid(s.shape) = 0;
```

`senate` has `6` Invalid Records of 100 ( 6% Invalid )

```sql
SELECT ST_IsValid(s.shape), s.* FROM `state` s WHERE ST_IsValid(s.shape) = 0;
```

`state` has `3` Invalid Records of 50 ( 6% Invalid )

```sql
SELECT ST_IsValid(z.shape), z.* FROM `zipcode` z WHERE ST_IsValid(z.shape) = 0;
```

`zipcode` has `4181` Invalid Records of 29810 ( 14% Invalid )

**Comment by manifestinteractive** [comment]
Here is a database dump of what is imported after the models and seeders are triggered.  If we can fix the data I can reimport them into seeders so we can fix the invalid indexing.

[civil_services_api.sql.zip](https://github.com/CivilServiceUSA/api/files/863441/civil_services_api.sql.zip)

**Comment by manifestinteractive** [comment]
Elastic Search Mappings:
---

Using `type: 'geo_shape'`

* https://github.com/CivilServiceUSA/api/blob/master/app/elasticsearch/create/house.js#L246-L248
* https://github.com/CivilServiceUSA/api/blob/master/app/elasticsearch/create/senate.js#L240-L242
* https://github.com/CivilServiceUSA/api/blob/master/app/elasticsearch/create/state.js#L112-L114
* https://github.com/CivilServiceUSA/api/blob/master/app/elasticsearch/create/geolocation.js#L82-L84

Seeder Files:
---

Using `shape: queryInterface.sequelize.fn('GeomFromText', 'SOME_GEOMETRY_DATA')`

*  https://raw.githubusercontent.com/CivilServiceUSA/api/master/app/seeders/20170301000000-house-seeder.js
* https://github.com/CivilServiceUSA/api/blob/master/app/seeders/20170101000000-senate-seeder.js#L57
* https://github.com/CivilServiceUSA/api/blob/master/app/seeders/20170101000000-state-seeder.js#L26
* https://github.com/CivilServiceUSA/api/blob/master/app/seeders/20170301000000-zipcode-00-seeder.js#L16

**Comment by johnkramlich** [comment]
I attempted the ST_buffer(geometry,0.00001) trick mentioned here without much luck. http://stackoverflow.com/questions/35594266/invalid-geometry-mysql  

After quite a bit of searching I came across this post describing valid vs invalid geometries:
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=liblwgeom-4.0

My next step is to attempt to fix the invalid geometries with SpatiaLite + SQLite , export them, and then reimport them to MySQL.  My assumption is that if MySQL considers them valid, so will ElasticSearch.

**Comment by manifestinteractive** [comment]
@johnkramlich Thanks for digging into this too.  I have tried the following without success:

1. Use different GeoJSON data for the original import into MySQL
2. Export the MySQL column as GeoJSON and try running it through CLI tools that simplify GeoJSON shapes
3. Asking it politely to work

**Comment by bjmc** [comment]
The link @johnkramlich mentions that `ST_MakeValid()` is supported by PostGIS. I'm trying to use [pgloader](http://pgloader.io/) to import the MySQL data into Postgres and perhaps correct it there.

**Comment by manifestinteractive** [comment]
@bjmc Just a heads up that I am about 15 minutes from wrapping up this fix.  The issue was some of the GeoJSON data that had edges that overlapped back onto themselves.  I am manually fixing the `house`, `state` & `senate` data and will work on the zip codes later.

Going to go ahead and close out this issue since we have the important stuff getting wrapped up.

**Comment by bjmc** [comment]
Actually, instead of trying to export from MySQL to Postgres, I think it'll probably be easier to just run the seeder files against a PostGIS database to start with.

**Comment by bjmc** [comment]
Ah, glad to hear it. :+1:
