### ISSUE TITLE
Add data for Puerto Rico senators

### ISSUE THREAD

**Issue by pgacv2** [CivilServiceUSA/api#40]
#### Overview:

The legislators endpoint is not returning data for Puerto Rico senators.

#### Acceptance Criteria:

Return data as listed here: http://senado.pr.gov/Pages/Senadores.aspx

#### Steps to Duplicate _( required for bug reports )_:

https://api.civil.services/v1/legislators/?apikey=KEY&zipcode=00926

You can use any zip code in Puerto Rico.

**Comment by manifestinteractive** [comment]
@pgacv2 The US Senate Data for this project is pulled in from data in this repository:

https://github.com/CivilServiceUSA/us-senate

That repository pulls in data from a Spreadsheet we maintain online:

https://docs.google.com/spreadsheets/d/1sbkk-E9odeEa-AvmioYrrcmjgCZmOvZ_JlFlTiytzFY/edit?usp=sharing

Probably the simplest way to contribute to this project is to Request Edit permissions to that CSV file, and fill out any missing data ( in this case, pretty much all or Puerto Rico ) and let me know when that data is added.

From there I will also need to locate some reliable GeoJSON / Shapefiles for Puerto Rico, so if you know where I can find those, that will cut down a great deal of time.

Finally, for this project, I will also need 1024x1024px headshots for each senator in that area, so if those are not readily available on that website, then we'll need to track down some high quality ones for those as well.

Once all that stuff is collected, the rest is mostly just an automated process I can kick off.
