### ISSUE TITLE
VA zip code 22350 is "not found"

### ISSUE THREAD

**Issue by typpo** [CivilServiceUSA/api#42]
#### Overview:

The zip code 22350 is "not found" when you search for a senator.

#### Acceptance Criteria:

22350 should return senator and representative results because it is a zip code in northern Virginia.  VA's senators are Tim Kaine and Mark Warner.  According to house.gov, 22350 belongs to Virginia's 8th district and the representative is Donald Beyer.

#### Steps to Duplicate _( required for bug reports )_:

Example API request: https://api.civil.services/v1/senate/?apikey=XXX&zipcode=22350

Response:
```
{"notices":[],"warnings":[],"errors":["22350 Zip Code Not Found"],"field_errors":{},"meta":{"total":0,"showing":0,"pages":1,"page":1},"data":[], ...}
```

#### System Info _( required for bug reports )_:

Chrome 60

**Comment by manifestinteractive** [comment]
It looks like we do not have any `2235X` zip codes in our database.  For those that want to dig into this ticket, here is the file that needs updating:

https://github.com/CivilServiceUSA/api/blob/master/app/seeders/20170301000000-zipcode-22-seeder.js

**Comment by skylerkatz** [comment]
First stab at filling in this data in https://github.com/CivilServiceUSA/api/pull/43

**Comment by nickoneill** [comment]
Similar results for `20185`

@skylerkatz does your PR cover that zip as well? Do we know any other zip areas that are uncovered?

**Comment by skylerkatz** [comment]
@nickoneill This PR does not cover that zip, but I can add it to the PR this afternoon.
